/**
 * src/simhost/__tests__/lantern-shape.integration.test.ts
 *
 * The four real-board invariants behind the v0.2.4 to v0.2.7 fixes (M8 island
 * bleeds, M10 CD4000 rail default, M11 LM339 multi-unit wrapper, and the
 * fresh-tran-uic flow that used to abort), run in CI on a board that is IN the
 * repository's reach: a synthetic board generated by scripts/gen-synthetic-board.mjs
 * whose connectivity is modelled on the maintainer's private led_lantern rev B
 * (issue #23). The original real-board versions of these tests live in
 * floating-island.integration.test.ts behind CIRCSIM_PRIVATE_BOARDS_DIR and run
 * only where that private board exists; before this file, nothing in CI covered
 * them at all.
 *
 * The synthetic board is parsed with parseBoard like any user board, so the
 * whole parse -> extract -> resolve -> deck -> real ngspice path is exercised.
 *
 * Skipped with a visible message when resources/ngspice/<platform> is missing.
 */

import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import { generateBoard, lanternShape } from '../../../scripts/gen-synthetic-board.mjs'
import { parseBoard } from '../../core/kicad/board'
import { resolveAll } from '../../core/models/resolve'
import type { LibraryEntry, Resolution } from '../../core/models/types'
import { extract, suggestGround } from '../../core/netlist/extract'
import type { Circuit } from '../../core/netlist/extract'
import { generateDeck } from '../../core/spicegen/generate'
import type { Instrument } from '../../core/spicegen/instruments'
import { SimHost } from '../index'
import { ngspiceResourcesAvailable } from '../ngspiceFfi'
import type { SimEvent } from '../protocol'

const haveNgspice = ngspiceResourcesAvailable()
if (!haveNgspice) {
  console.warn('[lantern-shape] resources/ngspice/<platform> missing: the lantern-shape invariants are SKIPPED (run npm run fetch:ngspice)')
}

const MODELS = join(process.cwd(), 'resources', 'models')

interface Setup {
  circuit: Circuit
  resolutions: Resolution[]
  modelTexts: Record<string, string>
  gndId: number
}

function load(): Setup {
  const board = parseBoard(generateBoard(lanternShape(10)))
  const library = (JSON.parse(readFileSync(join(MODELS, 'index.json'), 'utf8')) as { entries: LibraryEntry[] }).entries
  const modelTexts: Record<string, string> = {}
  for (const f of readdirSync(MODELS)) {
    if (f === 'index.json') continue
    if (f.endsWith('.lib') || f.endsWith('.json')) modelTexts[f] = readFileSync(join(MODELS, f), 'utf8')
  }
  const probe = extract(board)
  const gnd = suggestGround(probe.nets)
  if (!gnd) throw new Error('no ground suggested for the lantern-shape board')
  const circuit = extract(board, { groundNetId: gnd.id })
  return { circuit, resolutions: resolveAll(circuit, undefined, undefined, library), modelTexts, gndId: gnd.id }
}

function makeDeck(setup: Setup, supplyNetId: number): string[] {
  const instruments: Instrument[] = [
    { kind: 'ground-ref', netId: setup.gndId },
    { kind: 'dc-supply', id: 'auto-supply', netId: supplyNetId, volts: 5, seriesOhms: 0.1 }
  ]
  return generateDeck({
    circuit: setup.circuit,
    resolutions: setup.resolutions,
    instruments,
    groundNetId: setup.gndId,
    title: 'lantern-shape.kicad_pcb',
    modelTexts: setup.modelTexts
  })
}

/** Load a deck into a FRESH SimHost and run `tran <tstep> <tstop> uic` (the app flow). */
async function runFreshTranUic(deck: string[], tstep: string, tstop: string): Promise<{ rows: number; errs: string[] }> {
  const events: SimEvent[] = []
  const host = new SimHost({ emit: (e) => events.push(e), disableWatchdog: true })
  try {
    await host.start()
    host.handleCommand({ type: 'loadCircuit', deckLines: deck })
    await host.whenIdle()
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const engine = (host as any).engine
    await engine.command(`tran ${tstep} ${tstop} uic`, true)
    const plot = engine.currentPlot()
    let rows = 0
    for (const name of engine.allVectors(plot)) {
      if (name.toLowerCase() === 'time') {
        const d = engine.vectorData(name)
        rows = d ? d.length : 0
      }
    }
    const errs = (events.filter((e) => e.type === 'log' && e.level === 'error') as Extract<SimEvent, { type: 'log' }>[]).map(
      (e) => e.text
    )
    return { rows, errs }
  } finally {
    await host.dispose()
  }
}

describe.skipIf(!haveNgspice)('lantern-shape board: M8 / M10 / M11 invariants in CI', () => {
  it('the board parses to the intended shape (guards the fixture, not the code under test)', () => {
    const setup = load()
    expect(setup.circuit.parts.length).toBeGreaterThanOrEqual(20)
    const names = new Set(setup.circuit.nets.map((n) => n.kicadName))
    for (const n of ['/PACK+', '/VGATED', '/LED1_K', '/LED1_DRIVE', '/LED3_K', '/LED4_K', '/GAUGE_C3', '/GAUGE_C4']) {
      expect(names.has(n), `net ${n}`).toBe(true)
    }
  })

  it('M8: stranded LED nets are bled; nets attached through the LM339 outputs are not', () => {
    const setup = load()
    const pack = setup.circuit.nets.find((n) => n.kicadName === '/PACK+')!
    const deck = makeDeck(setup, pack.id)
    const bleedNodes = deck.filter((l) => l.startsWith('r_float_')).map((l) => l.split(/\s+/)[1])
    for (const node of ['_led3_k', '_gauge_c3', '_led4_k', '_gauge_c4']) {
      expect(bleedNodes, `no bleed for ${node} (attached via x_u5 since M11)`).not.toContain(node)
    }
    for (const node of ['_led1_k', '_led1_drive']) {
      expect(bleedNodes, `bleed for ${node}`).toContain(node)
    }
    expect(deck).toContain('* floating-island bleed resistors (no DC path to ground)')
  })

  it('M10: the CD4000 parts keep the 12 V family default; their VDD rides /VGATED, not the bench-supplied /PACK+ net', () => {
    const setup = load()
    const pack = setup.circuit.nets.find((n) => n.kicadName === '/PACK+')!
    const vgated = setup.circuit.nets.find((n) => n.kicadName === '/VGATED')!
    const u7 = setup.circuit.parts.find((p) => p.ref === 'U7')
    const u8 = setup.circuit.parts.find((p) => p.ref === 'U8')
    expect(u7!.padNet.get('14'), 'U7 VDD pad net').toBe(vgated.id)
    expect(u8!.padNet.get('14'), 'U8 VDD pad net').toBe(vgated.id)
    expect(pack.id).not.toBe(vgated.id)

    const text = makeDeck(setup, pack.id).join('\n')
    expect(text).toContain('b_u7_1 ')
    expect(text).toContain('> 6.0000 ? 7.2000 : 4.8000)) ? 0 : 12.0000')
    expect(text).toContain('.model dacm_u8 dac_bridge(out_low=0 out_high=12.0000)')
    expect(text).not.toContain('vhigh:')
  })

  it('M11: U5 (LM339) resolves to the LM339_QUAD wrapper with all four units wired (14 nodes on x_u5)', () => {
    const setup = load()
    const u5 = setup.resolutions.find((r) => r.ref === 'U5')
    expect(u5, 'U5 must have a resolution').toBeDefined()
    expect(u5!.status).toBe('ok')
    expect(u5!.model?.kind).toBe('subckt')
    if (u5!.model?.kind === 'subckt') expect(u5!.model.subcktName).toBe('LM339_QUAD')
    const pack = setup.circuit.nets.find((n) => n.kicadName === '/PACK+')!
    const xLine = makeDeck(setup, pack.id).find((l) => l.startsWith('x_u5'))
    expect(xLine, 'deck must carry an x_u5 card').toBeDefined()
    const tokens = xLine!.trim().split(/\s+/)
    expect(tokens[tokens.length - 1]).toBe('LM339_QUAD')
    expect(tokens.length - 2, `x_u5 node count (card: ${xLine})`).toBe(14)
  })

  it('the full-board fresh tran-uic (the app flow that used to abort) produces data rows', async () => {
    const setup = load()
    const pack = setup.circuit.nets.find((n) => n.kicadName === '/PACK+')!
    const { rows, errs } = await runFreshTranUic(makeDeck(setup, pack.id), '1e-5', '1e-2')
    expect(errs).toEqual([])
    expect(rows).toBeGreaterThan(0)
  }, 120_000)
})
