/**
 * core/kicad/__tests__/board-versions.test.ts
 *
 * The "KiCad 6 to 10" support claim, tested on the syntax each version writes
 * (issue #63). Before this file every fixture and sample was KiCad 7 (20221018)
 * apart from one KiCad 10 file misnamed "v9"; nothing ran KiCad 6, 8 or 9.
 *
 * fixtures/synthetic/dialect-probe-kicad{6,7,8,9,10}.kicad_pcb carry the SAME
 * board (two F.Cu resistors, one rotated B.Cu capacitor, a track, a via, a zone,
 * an outline) in the dialect of each format generation:
 *
 *   KiCad 6   20211014  numeric nets, fp_text reference, (tstamp)
 *   KiCad 7   20221018  numeric nets, fp_text reference, (tstamp), (stroke)
 *   KiCad 8   20240108  numeric nets, (property "Reference"), (uuid)
 *   KiCad 9   20241229  numeric nets, B.Cu renumbered to layer 2
 *   KiCad 10  20260206  name-only nets (no net table, no numeric ids)
 *
 * The fixtures are generated by scripts/gen-synthetic-board.mjs and verified
 * against kicad-cli in the corpus suite (test/corpus/synthetic.corpus.test.ts).
 * The corpus suite additionally parses KiCad-written boards from each version.
 *
 * The parser's result must be identical across dialects once net ids (a
 * per-file detail) are replaced by net names.
 */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import { FORMAT_VERSIONS } from '../../../../scripts/gen-synthetic-board.mjs'
import { extract } from '../../netlist/extract'
import { parseBoard } from '../board'
import type { BoardModel } from '../types'

const FIXTURE_DIR = join(__dirname, '../../../../fixtures/synthetic')
const MAJORS = [6, 7, 8, 9, 10] as const

function load(major: number): { text: string; board: BoardModel } {
  const text = readFileSync(join(FIXTURE_DIR, `dialect-probe-kicad${major}.kicad_pcb`), 'utf8')
  return { text, board: parseBoard(text) }
}

/** Net-id-free view of everything the parser produces. */
function normalize(board: BoardModel): unknown {
  const name = (id: number | undefined): string | null => (id === undefined ? null : (board.netById.get(id)?.name ?? '?'))
  return {
    nets: [...board.netById.values()].map((n) => n.name).sort(),
    footprints: board.footprints.map((f) => ({
      ref: f.ref,
      value: f.value,
      libId: f.libId,
      layer: f.layer,
      at: f.at,
      pads: f.pads.map((p) => ({ number: p.number, type: p.type, shape: p.shape, at: p.at, size: p.size, net: name(p.netId) }))
    })),
    tracks: board.tracks.map((t) => ({ kind: t.kind, start: t.start, end: t.end, widthMm: t.widthMm, layer: t.layer, net: name(t.netId) })),
    vias: board.vias.map((v) => ({ at: v.at, sizeMm: v.sizeMm, drillMm: v.drillMm, layers: v.layers, net: name(v.netId) })),
    zones: board.zones.map((z) => ({ layer: z.layer, net: name(z.netId), polygon: z.polygon })),
    outline: board.outline.outer,
    edgeCuts: board.edgeCuts.length
  }
}

describe.each(MAJORS)('KiCad %i dialect', (major) => {
  it(`file header is format version ${FORMAT_VERSIONS[major]}`, () => {
    const { text } = load(major)
    expect(text).toContain(`(version ${FORMAT_VERSIONS[major]})`)
  })

  it('parses footprints with references, layers, rotation and pad nets', () => {
    const { board } = load(major)
    expect(board.footprints.map((f) => f.ref)).toEqual(['R1', 'R2', 'C1'])
    const [r1, r2, c1] = board.footprints
    expect(r1.value).toBe('10k')
    expect(r1.layer).toBe('F')
    expect(r1.at).toEqual({ x: 110, y: 110, rotDeg: 90 })
    expect(r2.at.rotDeg).toBe(0)
    expect(c1.layer).toBe('B')
    expect(c1.at.rotDeg).toBe(45)
    const netName = (id: number | undefined) => board.netById.get(id as number)?.name
    expect(r1.pads.map((p) => netName(p.netId))).toEqual(['VIN', 'MID'])
    expect(r2.pads.map((p) => netName(p.netId))).toEqual(['MID', 'GND'])
    expect(c1.pads.map((p) => netName(p.netId))).toEqual(['MID', 'GND'])
  })

  it('parses the track, via, zone and outline', () => {
    const { board } = load(major)
    expect(board.tracks).toHaveLength(1)
    expect(board.tracks[0].layer).toBe('F.Cu')
    expect(board.netById.get(board.tracks[0].netId)?.name).toBe('MID')
    expect(board.tracks[0].widthMm).toBeCloseTo(0.25)
    expect(board.vias).toHaveLength(1)
    expect(board.netById.get(board.vias[0].netId as number)?.name).toBe('GND')
    expect(board.zones).toHaveLength(1)
    expect(board.zones[0].layer).toBe('B.Cu')
    expect(board.netById.get(board.zones[0].netId as number)?.name).toBe('GND')
    expect(board.zones[0].polygon[0]).toHaveLength(4)
    expect(board.edgeCuts).toHaveLength(4)
    expect(board.outline.outer).toHaveLength(1)
    expect(board.outline.warnings).toEqual([])
  })

  it('extracts the same three-net circuit', () => {
    const { board } = load(major)
    const circuit = extract(board)
    expect(circuit.nets.map((n) => n.kicadName).sort()).toEqual(['GND', 'MID', 'VIN'])
    expect(circuit.parts).toHaveLength(3)
    // VIN reaches only R1 pad 1 (the probe has no source), everything else is wired.
    expect(circuit.warnings).toEqual([{ kind: 'single-pad-net', netName: 'VIN', ref: 'R1', pad: '1' }])
  })

  it('produces a result identical to KiCad 10 once net ids are replaced by names', () => {
    expect(normalize(load(major).board)).toEqual(normalize(load(10).board))
  })
})

describe('net format by KiCad generation', () => {
  it('KiCad 6 to 9 files carry a numeric net table; KiCad 10 (20260206) is name-only', () => {
    for (const major of [6, 7, 8, 9] as const) {
      expect(load(major).text, `KiCad ${major}`).toMatch(/\(net 1 "VIN"\)/)
    }
    const k10 = load(10).text
    expect(k10).not.toMatch(/\(net \d+/)
    expect(k10).toMatch(/\(net "VIN"\)/)
  })

  it('parseBoard synthesizes ids for name-only nets and keeps the file ids for numeric ones', () => {
    const legacy = load(8).board
    expect([...legacy.netById.keys()].sort()).toEqual([1, 2, 3])
    expect(legacy.netById.get(1)?.name).toBe('VIN')
    const nameOnly = load(10).board
    expect(nameOnly.netById.size).toBe(3)
    expect([...nameOnly.netById.values()].map((n) => n.name).sort()).toEqual(['GND', 'MID', 'VIN'])
  })
})
