/**
 * core/critic/__tests__/synthetic-layout.test.ts
 *
 * Critic geometry tested on a real layout (issue #48). Every other critic test
 * builds an inline board of unrotated, front-side, zone-free straight tracks, so
 * none of them can tell a correct pad transform from an inverted one. This suite
 * uses fixtures/synthetic/routed-rotated-kicad10.kicad_pcb: footprints at 30, 45,
 * 90 and 270 degrees, three parts on B.Cu (one rotated), tracks on both copper
 * layers, vias, a B.Cu ground pour and an F.Cu supply pour. The fixture is
 * generated by scripts/gen-synthetic-board.mjs, and KiCad itself (kicad-cli, in
 * the corpus suite) is the authority on where every pad sits:
 * fixtures/synthetic/routed-rotated-kicad10.kicad-pads.json holds KiCad's pad
 * centres, so the assertions here are against KiCad, not against circsim's
 * renderer.
 *
 * KNOWN DEFECTS. Two assertions encode behavior circsim gets wrong today and are
 * written with `it.fails` (they pass while the defect exists, and FAIL the moment
 * it is fixed, telling the fixer to flip the flag below):
 *   - #3  pad rotation has the wrong handedness (geom.ts padWorldPos);
 *   - #11 the clearance check compares centerlines and ignores track width.
 */

import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import { generateBoard } from '../../../../scripts/gen-synthetic-board.mjs'
import { parseBoard } from '../../kicad/board'
import type { BoardModel, Footprint, Pad, Vec2 } from '../../kicad/types'
import { extract } from '../../netlist/extract'
import { padWorldPos, segPointDistanceMm, trackResistanceOhms } from '../geom'
import { runCritic } from '../run'

/** Flip to false when #3 (pad rotation handedness) is fixed. */
const KNOWN_BUG_3_OPEN = true
/** Flip to false when #11 (clearance ignores track width) is fixed. */
const KNOWN_BUG_11_OPEN = true

const itBug3 = KNOWN_BUG_3_OPEN ? it.fails : it
const itBug11 = KNOWN_BUG_11_OPEN ? it.fails : it

const FIXTURE_DIR = join(__dirname, '../../../../fixtures/synthetic')
const board = parseBoard(readFileSync(join(FIXTURE_DIR, 'routed-rotated-kicad10.kicad_pcb'), 'utf8'))
const golden = (
  JSON.parse(readFileSync(join(FIXTURE_DIR, 'routed-rotated-kicad10.kicad-pads.json'), 'utf8')) as {
    pads: { ref: string; pad: string; net: string; x: number; y: number }[]
  }
).pads

const fpByRef = new Map(board.footprints.map((f) => [f.ref, f]))
const netName = (id: number | undefined): string | undefined => (id === undefined ? undefined : board.netById.get(id)?.name)

// --- helpers ------------------------------------------------------------------

function inPolygon(p: Vec2, ring: Vec2[]): boolean {
  let inside = false
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const a = ring[i]
    const b = ring[j]
    if (a.y > p.y !== b.y > p.y && p.x < ((b.x - a.x) * (p.y - a.y)) / (b.y - a.y) + a.x) inside = !inside
  }
  return inside
}

/** What same-net copper lies under point p for this pad ('track' | 'via' | 'zone'), or undefined. */
function copperUnder(b: BoardModel, pad: Pad, netId: number, p: Vec2): string | undefined {
  const through = pad.type !== 'smd'
  const padLayer = pad.layers.find((l) => l.endsWith('.Cu') && !l.startsWith('*'))
  const onLayer = (layer: string): boolean => through || layer === padLayer
  const tol = 0.01
  for (const t of b.tracks) {
    if (t.netId !== netId || !onLayer(t.layer)) continue
    if (segPointDistanceMm(t.start, t.end, p) <= t.widthMm / 2 + tol) return 'track'
  }
  for (const v of b.vias) {
    if (v.netId !== netId) continue
    if (Math.hypot(v.at.x - p.x, v.at.y - p.y) <= v.sizeMm / 2 + tol) return 'via'
  }
  for (const z of b.zones) {
    if (z.netId !== netId || !onLayer(z.layer)) continue
    if (z.polygon.some((ring) => inPolygon(p, ring))) return 'zone'
  }
  return undefined
}

function nettedPads(): { fp: Footprint; pad: Pad; netId: number }[] {
  const out: { fp: Footprint; pad: Pad; netId: number }[] = []
  for (const fp of board.footprints) {
    for (const pad of fp.pads) if (pad.netId !== undefined) out.push({ fp, pad, netId: pad.netId })
  }
  return out
}

// --- the fixture really has the layout the old tests lacked -------------------

describe('routed-rotated fixture', () => {
  it('contains rotated and back-side parts, both copper layers, vias and pours', () => {
    const angles = new Set(board.footprints.map((f) => ((f.at.rotDeg % 360) + 360) % 360))
    for (const a of [0, 30, 45, 90, 270]) expect(angles.has(a), `a footprint at ${a} degrees`).toBe(true)
    expect(board.footprints.filter((f) => f.layer === 'B').length).toBeGreaterThanOrEqual(3)
    expect(board.footprints.some((f) => f.layer === 'B' && f.at.rotDeg % 90 !== 0)).toBe(true)
    expect(new Set(board.tracks.map((t) => t.layer))).toEqual(new Set(['F.Cu', 'B.Cu']))
    expect(board.vias.length).toBeGreaterThanOrEqual(3)
    expect(new Set(board.zones.map((z) => z.layer))).toEqual(new Set(['F.Cu', 'B.Cu']))
    expect(board.outline.outer).toHaveLength(1)
  })

  it('has KiCad golden centres for every netted pad', () => {
    expect(golden.length).toBe(nettedPads().length)
    for (const g of golden) {
      const fp = fpByRef.get(g.ref)!
      expect(netName(fp.pads.find((p) => p.number === g.pad)?.netId), `${g.ref}.${g.pad}`).toBe(g.net)
    }
  })
})

// --- geometry against KiCad ---------------------------------------------------

describe('pad geometry against KiCad-derived positions', () => {
  it('every netted pad has same-net copper (track, via or zone) under its KiCad centre', () => {
    const missing: string[] = []
    for (const g of golden) {
      const fp = fpByRef.get(g.ref)!
      const pad = fp.pads.find((p) => p.number === g.pad)!
      if (!copperUnder(board, pad, pad.netId!, { x: g.x, y: g.y })) missing.push(`${g.ref}.${g.pad} (${g.net})`)
    }
    expect(missing, 'pads with no same-net copper at their KiCad centre').toEqual([])
  })

  itBug3('padWorldPos equals KiCad pad centres on rotated and back-side footprints (known bug #3)', () => {
    const wrong: string[] = []
    for (const g of golden) {
      const fp = fpByRef.get(g.ref)!
      const pad = fp.pads.find((p) => p.number === g.pad)!
      const w = padWorldPos(fp, pad)
      if (Math.hypot(w.x - g.x, w.y - g.y) > 1e-3) wrong.push(`${g.ref}.${g.pad}`)
    }
    expect(wrong, 'pads whose critic position differs from KiCad').toEqual([])
  })

  itBug3('every netted pad has same-net copper under the position the critic computes (known bug #3)', () => {
    const missing: string[] = []
    for (const { fp, pad, netId } of nettedPads()) {
      if (!copperUnder(board, pad, netId, padWorldPos(fp, pad))) missing.push(`${fp.ref}.${pad.number}`)
    }
    expect(missing).toEqual([])
  })
})

// --- critic checks that consume pad positions ---------------------------------

describe('critic on the routed-rotated board', () => {
  it('runs every check and finds nothing on a clean, fully routed board with no simulation', () => {
    const report = runCritic(board, extract(board))
    expect(report.findings).toEqual([])
    expect(report.ranBy).toEqual(expect.arrayContaining(['floating', 'clearance', 'decoupling', 'loop-area']))
  })

  itBug3('IR drop on VIN is attributed to the R1 sink at the value the KiCad geometry gives (known bug #3)', () => {
    const circuit = extract(board)
    const vin = circuit.nets.find((n) => n.kicadName === 'VIN')!
    const report = runCritic(board, circuit, { nodeVoltages: { [vin.spiceNode]: 5 }, partCurrents: { R1: 10 } })
    const f = report.findings.find((x) => x.check === 'ir-drop' && x.netId === vin.id)
    expect(f, 'an IR-drop finding for VIN').toBeDefined()

    // Path J1.1 -> R1.1 is the single 0.4 mm F.Cu track between the two KiCad
    // pad centres; the check carries all 10 A of R1 over it.
    const j1 = golden.find((g) => g.ref === 'J1' && g.pad === '1')!
    const r1 = golden.find((g) => g.ref === 'R1' && g.pad === '1')!
    const lengthMm = Math.hypot(r1.x - j1.x, r1.y - j1.y)
    const expectedDropV = 10 * trackResistanceOhms(lengthMm, 0.4, 1)
    expect(f!.metrics!.dropV).toBeCloseTo(expectedDropV, 3)
    expect(f!.refs).toContain('R1')
  })
})

describe('clearance on synthetic copper', () => {
  function twoTracks(widthMm: number, offsetMm: number, layerB = 'F.Cu'): ReturnType<typeof parseBoard> {
    return parseBoard(
      generateBoard({
        kicad: 10,
        nets: ['A', 'B'],
        footprints: [],
        tracks: [
          { net: 'A', layer: 'F.Cu', width: widthMm, pts: [[100, 100], [120, 100]] },
          { net: 'B', layer: layerB, width: widthMm, pts: [[100, 100 + offsetMm], [120, 100 + offsetMm]] }
        ]
      })
    )
  }
  const clearanceFindings = (b: BoardModel) =>
    runCritic(b, extract(b)).findings.filter((f) => f.check === 'clearance')

  it('control: tracks 3 mm apart produce no clearance finding', () => {
    expect(clearanceFindings(twoTracks(0.25, 3))).toEqual([])
  })

  it('control: overlapping copper on DIFFERENT layers is not a clearance problem', () => {
    expect(clearanceFindings(twoTracks(1.0, 0.6, 'B.Cu'))).toEqual([])
  })

  it('centerlines that touch are an error', () => {
    const f = clearanceFindings(twoTracks(0.25, 0))
    expect(f).toHaveLength(1)
    expect(f[0].severity).toBe('error')
  })

  itBug11('two 1.0 mm tracks whose copper overlaps by 0.4 mm (centerlines 0.6 mm apart) are a clearance error (known bug #11)', () => {
    // Centerline distance 0.6 mm clears the 0.2 mm minimum, but the copper edges
    // are 0.6 - 1.0 = -0.4 mm apart: the tracks are shorted.
    const f = clearanceFindings(twoTracks(1.0, 0.6))
    expect(f).toHaveLength(1)
    expect(f[0].severity).toBe('error')
  })
})
